username = 'Marko'
scans_directory = '/home/marko/dev/scan-mergepdf-send/scans'
merge_directory = '/home/marko/dev/scan-mergepdf-send/merged'
archive_directory = '/home/marko/dev/scan-mergepdf-send/archive'
# my_email = 'marko@markoantolos.com'
my_email = 'info@bilanca-usluge.hr'
